// <auto-generated />
namespace AAMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class attendancedataedit5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attendancedataedit5));
        
        string IMigrationMetadata.Id
        {
            get { return "202201311801398_attendance data edit 5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
