// <auto-generated />
namespace AAMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editedmodels5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedmodels5));
        
        string IMigrationMetadata.Id
        {
            get { return "202201211113161_edited-models5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
